# Default values for cilium
nameOverride: ""
fullnameOverride: ""          # Examples use "cilium"

global:
  domain_kube: cluster.local  # Kubernetes cluster domain (used by etcd-operator)

rbac:
  enable: true                # Enables all RBAC resources

psp:
  enable: true                # Enables PodSecurityPolicies for all components
                              # (and RBAC bindings, regardless of rbac.enable)

preflight:                    # Enable pre-flight check of nodes before install
  enable: true
  # Remove preflight remains
  deletePolicy: hook-failed,hook-succeeded,before-hook-creation

operator:
  enable: true
  image:
    registry: docker.io
    repository: cilium/operator
    tag: v1.5.0-rc4
    pullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  hostAliases: []                    # Add entries to hosts
  #  - ip: "1.2.3.4"
  #    hostnames:
  #    - "kube.example.com"
  annotations: {}
  labels: {}
  affinity: {}                       # Affinity, to schedule only on 'master' nodes:
    #nodeAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    nodeSelectorTerms:
    #    - matchExpressions:
    #       - key: kubernetes.io/role
    #         operator: In
    #         values:
    #         - master
  tolerations: {}
  env: []
  # - name: IMATEAPOT
  #   value: 42
  config:
    debug: false  # Enable debugging mode
    #api-server-port: 9234               # Port on which the operator should serve API requests (default 9234)
    #cilium-endpoint-gc: true            # Enable CiliumEndpoint garbage collector (default true)
    #identity-gc-interval: 10m0s         # GC interval for security identities (default 10m0s)
    #synchronize-k8s-services: true      # Synchronize Kubernetes services to kvstore (default true)
    #unmanaged-pod-watcher-interval: 15  # Interval to check for unmanaged kube-dns pods (0 to disable) (default 15)
    #disable-endpoint-crd: false         # If you want to disable endpoint CRD generation, enable this


etcd:
  #endpoints:                           # unused with operator
  #- http://EDIT-ME-ETCD-ADDRESS:2379
  secretName:                           # default {fullname}-etcd
  #secretVolume:                        # Override the secret volume mount, e.g.:
  #  hostPath:
  #    path: /var/lib/minikube/certs/
  #    type: DirectoryOrCreate
  operator:
    enable: true
    image:
      registry: docker.io
      repository: cilium/cilium-etcd-operator
      tag: v2.0.6
      pullPolicy: IfNotPresent

    dnsPolicy: ClusterFirstWithHostNet
    hostAliases: []
    annotations: {}
    labels: {}
    affinity: {}
    tolerations: {}
    env: []
    cluster_size: 3                    # Spawn etcd clusters of this size


agent:
  image:
    registry: docker.io
    repository: cilium/cilium
    tag: v1.5.0-rc4
    pullPolicy: IfNotPresent

  init_image:
    registry: docker.io
    repository: cilium/cilium-init
    tag: 2019-04-05
    pullPolicy: IfNotPresent

  dnsPolicy: ClusterFirstWithHostNet
  hostAliases: []
  annotations: {}
  labels: {}
  affinity: {}
  tolerations:
  - operator: Exists    # Tolerate all taints

  env: []               # Additional environment for the DaemonSet

  runtime: docker       # container runtime, docker|containerd|crio
  ipsec:
    enable: false
    secretName:         # default {fullname}-ipsec
  clustermesh:
    secretName:         # default {fullname}-clustermesh

  # If a serious issue occurs during Cilium startup, this
  # invasive option may be set to true to remove all persistent
  # state. Endpoints will not be restored using knowledge from a
  # prior Cilium run, so they may receive new IP addresses upon
  # restart. This also triggers clean-cilium-bpf-state.
  clean-cilium-state: false
  # If you want to clean cilium BPF state, set this to true;
  # Removes all BPF maps from the filesystem. Upon restart,
  # endpoints are restored with the same IP addresses, however
  # any ongoing connections may be disrupted briefly.
  # Loadbalancing decisions will be reset, so any ongoing
  # connections via a service may be loadbalanced to a different
  # backend after restart.
  clean-cilium-bpf-state: false

  # wait-bpf-mount makes init container wait until bpf filesystem is mounted
  wait-bpf-mount: false


config:
  debug: false  # If you want to run cilium in debug mode change this value to true

  # If you want metrics enabled in all of your Cilium agents, set
  # the port for which the Cilium agents will have their metrics exposed.
  # NOTE that this will open the port on ALL nodes where Cilium pods are scheduled.
  # prometheus-serve-addr: ":9090"

  enable-ipv4: true   # Enable IPv4 addressing. If enabled, all endpoints are allocated an IPv4 address.
  enable-ipv6: false  # Enable IPv6 addressing. If enabled, all endpoints are allocated an IPv6 address.

  # In Cilium 1.0, all traffic from the host, including from local processes
  # and traffic that is masqueraded from the outside world to the host IP,
  # would be classified as from the host entity (reserved:host label).
  # Furthermore, to allow Kubernetes agents to perform health checks over IP
  # into the endpoints, the host is allowed by default. This means that all
  # traffic from the outside world is also allowed by default, regardless of
  # security policy.
  #
  # This option was introduced in Cilium 1.1 to disable this behaviour. It must
  # be explicitly set to "false" to take effect on Cilium 1.3 or earlier.
  # Cilium 1.4 sets this to "false" by default if it is not specified in the
  # ConfigMap.
  #
  # This option has been deprecated, it will be removed in Cilium 1.5 or later.
  #
  # For more information, see https://cilium.link/host-vs-world
  #legacy-host-allows-world: "false"

  # If you want cilium monitor to aggregate tracing for packets, set this level
  # to "low", "medium", or "maximum". The higher the level, the less packets
  # that will be seen in monitor output.
  monitor-aggregation-level: none

  # bpf-ct-global-*-max specifies the maximum number of connections
  # supported across all endpoints, split by protocol: tcp or other. One pair
  # of maps uses these values for IPv4 connections, and another pair of maps
  # use these values for IPv6 connections.
  #
  # If these values are modified, then during the next Cilium startup the
  # tracking of ongoing connections may be disrupted. This may lead to brief
  # policy drops or a change in loadbalancing decisions for a connection.
  #
  # For users upgrading from Cilium 1.2 or earlier, to minimize disruption
  # during the upgrade process, comment out these options.
  bpf-ct-global-tcp-max: 524288
  bpf-ct-global-any-max: 262144

  # Pre-allocation of map entries allows per-packet latency to be reduced, at
  # the expense of up-front memory allocation for the entries in the maps. The
  # default value below will minimize memory usage in the default installation;
  # users who are sensitive to latency may consider setting this to "true".
  #
  # This option was introduced in Cilium 1.4. Cilium 1.3 and earlier ignore
  # this option and behave as though it is set to "true".
  #
  # If this value is modified, then during the next Cilium startup the restore
  # of existing endpoints and tracking of ongoing connections may be disrupted.
  # This may lead to policy drops or a change in loadbalancing decisions for a
  # connection for some time. Endpoints may need to be recreated to restore
  # connectivity.
  #
  # If this option is set to "false" during an upgrade from 1.3 or earlier to
  # 1.4 or later, then it may cause one-time disruptions during the upgrade.
  preallocate-bpf-maps: false

  # Regular expression matching compatible Istio sidecar istio-proxy
  # container image names
  sidecar-istio-proxy-image: cilium/istio_proxy

  # Encapsulation mode for communication between nodes
  # Possible values:
  #   - disabled
  #   - vxlan (default)
  #   - geneve
  tunnel: vxlan

  # Name of the cluster. Only relevant when building a mesh of clusters.
  cluster-name: default

  # Unique ID of the cluster. Must be unique across all connected clusters and
  # in the range of 1 and 255. Only relevant when building a mesh of clusters.
  #cluster-id: 1

  # Interface to be used when running Cilium on top of a CNI plugin.
  # For flannel, use "cni0"
  flannel-master-device: ''
  # When running Cilium with policy enforcement enabled on top of a CNI plugin
  # the BPF programs will be installed on the network interface specified in
  # 'flannel-master-device' and on all network interfaces belonging to
  # a container. When the Cilium DaemonSet is removed, the BPF programs will
  # be kept in the interfaces unless this option is set to "true".
  flannel-uninstall-on-exit: false
  # Installs a BPF program to allow for policy enforcement in already running
  # containers managed by Flannel.
  # NOTE: This requires Cilium DaemonSet to be running in the hostPID.
  # To run in this mode in Kubernetes change the value of the hostPID from
  # false to true. Can be found under the path `spec.spec.hostPID`
  flannel-manage-existing-containers: false

  # DNS Polling periodically issues a DNS lookup for each `matchName` from
  # cilium-agent. The result is used to regenerate endpoint policy.
  # DNS lookups are repeated with an interval of 5 seconds, and are made for
  # A(IPv4) and AAAA(IPv6) addresses. Should a lookup fail, the most recent IP
  # data is used instead. An IP change will trigger a regeneration of the Cilium
  # policy for each endpoint and increment the per cilium-agent policy
  # repository revision.
  #
  # This option is disabled by default starting from version 1.4.x in favor
  # of a more powerful DNS proxy-based implementation, see [0] for details.
  # Enable this option if you want to use FQDN policies but do not want to use
  # the DNS proxy.
  #
  # To ease upgrade, users may opt to set this option to "true".
  # Otherwise please refer to the Upgrade Guide [1] which explains how to
  # prepare policy rules for upgrade.
  #
  # [0] http://docs.cilium.io/en/stable/policy/language/#dns-based
  # [1] http://docs.cilium.io/en/stable/install/upgrade/#changes-that-may-require-action
  tofqdns-enable-poller: false

  #tofqdns-pre-cache:

  # Enable legacy services (prior v1.5) to prevent from terminating existing
  # connections with services when upgrading Cilium from < v1.5 to v1.5.
  enable-legacy-services: false


  #datapath-mode:
  #ipvlan-master-device:
  #install-iptables-rules:
  #masquerade:
  #auto-direct-node-routes:
