apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cilium.name" . }}
    helm.sh/chart: {{ include "cilium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: agent
  name: {{ template "cilium.fullname" . }}-config
data:
  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you follow the tutorial in https://cilium.link/etcd-config
  etcd-config: |-
    endpoints:
  {{- if .Values.etcd.endpoints }}
    {{ toYaml .Values.etcd.endpoints | indent 4 }}
  {{- else }}
   - https://{{ template "cilium.fullname" . }}-etcd-client.{{ .Release.Namespace }}.svc:2379
  {{- end }}
    #
    # In case you want to use TLS in etcd, uncomment the 'ca-file' line
    # and create a kubernetes secret by following the tutorial in
    # https://cilium.link/etcd-config
    ca-file: '/etc/pki/etcd/etcd-client-ca.crt'
    #
    # In case you want client to server authentication, uncomment the following
    # lines and create a kubernetes secret by following the tutorial in
    # https://cilium.link/etcd-config
    key-file: '/etc/pki/etcd/etcd-client.key'
    cert-file: '/etc/pki/etcd/etcd-client.crt'
{{ toYaml .Values.config | indent 2 }}
