{{/* vim: set filetype=mustache: */}}
{{- if .Values.etcd.operator.enable -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cilium.name" . }}
    helm.sh/chart: {{ include "cilium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: etcd-operator
  name: {{ template "cilium.fullname" . }}-etcd-operator
{{- end -}}
