{{/* vim: set filetype=mustache: */}}
{{- if .Values.operator.enable -}}
apiVersion: {{ include "apps.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cilium.name" . }}
    helm.sh/chart: {{ include "cilium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: operator
  name: {{ template "cilium.fullname" . }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.operator.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end -}}
      labels:
        app.kubernetes.io/name: {{ include "cilium.name" . }}
        helm.sh/chart: {{ include "cilium.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: operator
    {{- with .Values.operator.labels }}
{{ toYaml . | indent 8 }}
    {{- end -}}
    spec:
      containers:
      - args:
        - --debug=$(CILIUM_DEBUG)
        - --kvstore=etcd
        - --kvstore-opt=etcd.config=/etc/etcd.yml
        command:
        - cilium-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CILIUM_DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: cilium-config
              optional: true
        - name: CILIUM_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: cluster-name
              name: cilium-config
              optional: true
        - name: CILIUM_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: cluster-id
              name: cilium-config
              optional: true
        - name: CILIUM_DISABLE_ENDPOINT_CRD
          valueFrom:
            configMapKeyRef:
              key: disable-endpoint-crd
              name: cilium-config
              optional: true
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: cilium-aws
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: cilium-aws
              optional: true
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_DEFAULT_REGION
              name: cilium-aws
              optional: true
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        name: cilium-operator
        volumeMounts:
        - mountPath: /etc/etcd.yml
          subPath: etcd.yml
          name: etcd-config
          readOnly: true
        - mountPath: /etc/pki/etcd
          name: etcd-secrets
          readOnly: true
      dnsPolicy: {{ .Values.operator.dnsPolicy }}
      restartPolicy: Always
    {{- if semverCompare "<= 1.8-0" .Capabilities.KubeVersion.GitVersion }}
      serviceAccount: {{ template "cilium.fullname" . }}-operator
    {{- else }}
      serviceAccountName: {{ template "cilium.fullname" . }}-operator
    {{- end }}
    {{- with .Values.agent.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end -}}
      volumes:
      # To read the etcd config stored in config maps
      - configMap:
          defaultMode: 420
          items:
          - key: etcd-config
            path: etcd.yml
          name: {{ template "cilium.fullname" . }}-config
        name: etcd-config-path
        # To read the k8s etcd secrets in case the user might want to use TLS
      - name: etcd-secrets
        secret:
          defaultMode: 420
          optional: true
          secretName: cilium-etcd-secrets
{{- end -}}
