{{/* vim: set filetype=mustache: */}}
{{- if .Values.operator.enable -}}
apiVersion: {{ include "apps.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cilium.name" . }}
    helm.sh/chart: {{ include "cilium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: operator
  name: {{ template "cilium.fullname" . }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cilium-cm.yml") . | sha256sum }}
    {{- with .Values.operator.annotations }}
      {{ toYaml . | indent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "cilium.name" . }}
        helm.sh/chart: {{ include "cilium.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: operator
    {{- with .Values.operator.labels }}
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      containers:
      - command:
        - cilium-operator
        args:
        - --debug=$(CILIUM_DEBUG)
        - --config=/etc/cilium/config.yml
        env:
      {{- with .Values.operator.env }}
{{ toYaml . | indent 8 }}
      {{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CILIUM_DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: {{ template "cilium.fullname" . }}
              optional: true
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: cilium-aws
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: cilium-aws
              optional: true
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_DEFAULT_REGION
              name: cilium-aws
              optional: true
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        name: cilium-operator
        volumeMounts:
        - mountPath: /etc/cilium
          name: cilium-config
          readOnly: true
        - mountPath: /etc/pki/etcd
          name: etcd-secrets
          readOnly: true
      dnsPolicy: {{ .Values.operator.dnsPolicy }}
    {{- with .Values.agent.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
    {{- if semverCompare "<= 1.8-0" .Capabilities.KubeVersion.GitVersion }}
      serviceAccount: {{ template "cilium.fullname" . }}-operator
    {{- else }}
      serviceAccountName: {{ template "cilium.fullname" . }}-operator
    {{- end }}
    {{- with .Values.agent.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.operator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: cilium-config  # To read the configuration from the config map
        configMap:
          name: {{ template "cilium.fullname" . }}
          items:
          - key: etcd
            path: etcd.yml
          - key: cilium
            path: config.yml
          defaultMode: 420
      - name: etcd-secrets  # To read the k8s etcd secrets in case the user might want to use TLS
    {{- if hasKey .Values.etcd "secretVolume" }}
{{ toYaml .Values.etcd.secretVolume | indent 8 }}
    {{- else  }}
        secret:
          secretName: {{ .Values.etcd.secretName | default (printf "%s-etcd" (include "cilium.fullname" .)) }}
          defaultMode: 420
          optional: true
    {{- end }}
{{- end -}}
