{{/* vim: set filetype=mustache: */}}
{{- if .Values.rbac.create and .Values.operator.create -}}
apiVersion: {{ rbac.apiVersion }}
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cilium.name" . }}
    helm.sh/chart: {{ include "cilium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: operator
  name: {{ template "cilium.fullname" . }}-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - deployments
  - componentstatuses
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  - ciliumnetworkpolicies/status
  - ciliumendpoints
  - ciliumendpoints/status
  verbs:
  - '*'
---
apiVersion: {{ rbac.apiVersion }}
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "cilium.name" . }}
    helm.sh/chart: {{ include "cilium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: operator
  name: {{ template "cilium.fullname" . }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cilium.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ template "cilium.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
{{- end -}}
